services:
  postgres_db:
    image: postgres:15
    container_name: penguin_sql_challenge
    environment:
      POSTGRES_USER: juan_gonzalez
      POSTGRES_PASSWORD: penguin_password
      POSTGRES_DB: penguin_academy
    ports:
      - "5432:5432"
    volumes:
      # Esto vincula tu carpeta local 'data' con una carpeta dentro del contenedor
      - ./data:/container_data
      # Para que los datos no se borren si apagas el contenedor
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: